export default [
    {present: "seek", past: "sought", participle: "sought", spanish:"buscar", common:false},
    {present: "settle", past: "settled", participle: "settled", spanish:"resolver", common:false},
    {present: "approach", past: "approached", participle: "approached", spanish:"acercarse", common:false},
    {present: "throw", past: "threw", participle: "thrown", spanish:"lanzar", common:false},
    {present: "dismiss", past: "dismissed", participle: "dismissed", spanish:"descartar", common:false},
    {present: "hire", past: "hired", participle: "hired", spanish:"contratar", common:false},
    {present: "hide", past: "hid", participle: "hidden", spanish:"esconder", common:false},
    {present: "initialize", past: "initialized", participle: "initialized", spanish:"iniciar", common:false},
    {present: "earn", past: "earned", participle: "earned", spanish:"ganar", common:false},
    {present: "tease", past: "teased", participle: "teased", spanish:"bromear", common:false},
    {present: "punish", past: "punished", participle: "punished", spanish:"castigar", common:false},
    {present: "seal", past: "sealed", participle: "sealed", spanish:"sellar", common:false},
    {present: "struggle", past: "struggled", participle: "struggled", spanish:"luchar", common:false},
    {present: "spark", past: "sparked", participle: "sparked", spanish:"encender", common:false},
    {present: "achieve", past: "achieved", participle: "achieved", spanish:"lograr", common:false},
    {present: "grant", past: "granted", participle: "granted", spanish:"otorgar", common:false},
    {present: "lack", past: "lacked", participle: "lacked", spanish:"faltar", second_spanish_meaning:"carecer", common:true},
]
