export default [
    {present: "seem", past: "seemed", participle: "seemed", spanish:"parecer", common:true},
    {present: "hold", past: "held", participle: "held", spanish:"sostener", common:true},
    {present: "bring", past: "brought", participle: "brought", spanish:"traer", common:true},
    {present: "happen", past: "happened", participle: "happened", spanish:"suceder", common:true},
    {present: "provide", past: "provided", participle: "provided", spanish:"proveer", common:true},
    {present: "sit", past: "sat", participle: "sat", spanish:"sentarse", common:true},
    {present: "stand", past: "stood", participle: "stood", spanish:"estar", common:true},
    {present: "meet", past: "met", participle: "met", spanish:"reunir", second_spanish_meaning:"conocer",  common:true},
    {present: "include", past: "included", participle: "included", spanish:"incluir", common:true},
    {present: "set", past: "set", participle: "set", spanish:"establecer", common:true},
    {present: "learn", past: "learnt", participle: "learnt", spanish:"aprender", common:true},
    {present: "lead", past: "led", participle: "led", spanish:"liderar", common:true},
    {present: "understand", past: "understood", participle: "understood", spanish:"comprender", common:true},
    {present: "spend", past: "spent", participle: "spent", spanish:"gastar", common:true},
    {present: "grow", past: "grew", participle: "grown", spanish:"crecer", common:true},
    {present: "offer", past: "offered", participle: "offered", spanish:"ofrecer", common:true},
    {present: "appear", past: "appeared", participle: "appeared", spanish:"aparecer", common:true},
    {present: "serve", past: "served", participle: "served", spanish:"servir", common:true},
    {present: "send", past: "sent", participle: "sent", spanish:"enviar", common:true},
    {present: "stay", past: "stayed", participle: "stayed", spanish:"permanecer", common:true},
    {present: "fall", past: "fell", participle: "fallen", spanish:"caer", common:true},
    {present: "reach", past: "reached", participle: "reached", spanish:"alcanzar", common:true},
    {present: "remain", past: "remained", participle: "remained", spanish:"permanecer", common:true},
    {present: "suggest", past: "suggested", participle: "suggested", spanish:"sugerir", common:true},
    {present: "raise", past: "raised", participle: "raised", spanish:"elevar", common:true},
    {present: "pass", past: "passed", participle: "passed", spanish:"pasar", common:true},
    {present: "sell", past: "sold", participle: "sold", spanish:"vender", common:true},
    {present: "drop", past: "dropped", participle: "dropped", spanish:"tirar", common:false},
    {present: "chase", past: "chased", participle: "chased", spanish:"perseguir", common:false},
    {present: "avoid", past: "avoided", participle: "avoided", spanish:"evitar", common:false},
    {present: "require", past: "required", participle: "required", spanish:"requerir", common:true},
    {present: "expect", past: "expected", participle: "expected", spanish:"esperar", common:true},
    {present: "build", past: "built", participle: "built", spanish:"construir", common:true},
    {present: "carry", past: "carried", participle: "carried", spanish:"llevar", common:true},
]
